### ISSUE TITLE
Allow changing the log configuration in an ad-hoc way, to support interactive troubleshooting with more detailed logs.

### ISSUE THREAD

**Issue by vlvasilev** [gardener/logging#101]
**What would you like to be added**:
Allow changing the log configuration in an ad-hoc way, to support interactive troubleshooting with more detailed logs.

**Why is this needed**:
Uses case:
```text
I, as a developer suspect that something is going wrong in the api-server, related to `watch` events. 
I could then check the list of possible log messages. Then I’d see that they are logged on verbosity level 3 (i.e. they are hidden at the moment), 
then I’d activate them (this is the key piece that is currently not easy/practical/feasible) and would check if they yield any useful information for the issue at hand.
```

The idea came from @istvanballok  when he was debugging an api-server issue where the api-server was closing the long-lasting watch requests, and he didn’t find any relevant logs.
He thought that It could be that the implementation doesn’t write any relevant logs - or it could also be that the current log configuration just filters them out.

He suggested implementing a webhook similar to VPA which can either:
1. Execute a script to change the log level of a component or
2. Wrap the `entrypoint` in a shell script then, the developer can exec into the container and restart the process as needed.

He also suggests research/investigate how to extract the possible log messages of the main components from their source code, and make it easily searchable (e.g. a markdown file on GitHub) - to allow a developer to check for which module should he change the verbosity to get those logs.
But this could be left for another roadmap issue.

Some of our colleagues from the core team suggested that this is prone to leaving a lot of leftover configmaps and/or components with increased log levels.
As they suggested the simplest solution is to markdown the Shoot as failed and to change the log verbosity by hand.

On a follow-up chat, @wyb1 suggested adding the log level to the shoot spec under the KubeApiServer key [here](https://github.com/gardener/gardener/blob/e8eb807d790ff683e650b5918ddf64879863856a/example/90-shoot.yaml#L132).
But in this case, we are open to some kind of logging stack DOS attack.
@istvanballok said that logs obviously lose some of their value if they are filtered out. 
The approach of marking a shoot as failed, then changing the verbosity in the deployment could be feasible for a Gardener developer but He doubts that it is practised regularly in RCAs. 
It is not feasible for end-users - changing the shoot.yml could be a viable option for them.
On the other hand, having all the flexibility with an overloaded and hence unstable logging stack is also not desirable.

Unfortunately, fluent-bit log processing is a chain of a lot of filters and parsers and all of the logs are processed via Lua filters and our Output plugin is written in GO.
This makes fluent-bit extremely slow. The only way to control the logging throughput is to implement a throttling filter which could cut off some of the logs when the verbosity is increased.
At the moment as all of the control-plane components are deployed by Gardener developers, we assume that no one has malicious attention to break down the logging stack. Currently, our load test can handle only 10 times more logs from 100 shoots, and we have a delay of up to 10 minutes until all logs arrived in the Loki. 

On a cross-skipper meeting, Istvan talked about the generic mutating webhook idea, that would execute a script to manipulate the pod spec.
He also shared the idea to extract the possible log messages of the main components from their source code, and make it easily searchable (e.g. a markdown file on GitHub) - to allow a developer to check for which module should he change the verbosity to get those logs.

The participants were encouraging and haven’t pointed out showstoppers why it would be a bad idea.
So we have a green light to start developing a mutating webhook.

But the question is who will have the permission to change the log level? The operator, the user or both.
Should a specific expiration time be added to prevent forgetting of pods with increased log levels?
Should we implement a throttling filter and if so how to prevent it from deleting valuable logs?

**Comment by Kristian-ZH** [comment]
As this issue is not currently in the backlog and is not planed soon to be, I will close it for now and will open it once we take a decision to do this.
