### ISSUE TITLE
master-pull-request-job stuck during PR validation

### ISSUE THREAD

**Issue by Kristian-ZH** [gardener/logging#140]
**What happened**:
During the PR validation most of the time `master-pull-request-job` is stuck when it is built under `arm64` architecture.
The commands which can not finish successfully are the ones that are used to build the images:

`go build -mod=vendor -buildmode=c-shared -o build/out_loki.so ./cmd/fluent-bit-loki-plugin`

`CGO_ENABLED=0 GOOS=$(go env GOOS ) GOARCH=$(go env GOARCH) GO111MODULE=on go install -mod=vendor ./cmd/{event-logger|curator}`

These commands are called in [Docker containers](https://github.com/gardener/logging/blob/master/Dockerfile) which are created via [docker buildx build](https://docs.docker.com/build/buildx/).

The only workaround which we apply is to abort the job and to retrigger it after that. This procedure is repeated until the build jib finishes successfully.

**What you expected to happen**:
The job should finish successfully for correct PR.

**How to reproduce it (as minimally and precisely as possible)**:
Currently, we can not reproduce either locally or in a docker container. It can be seen only in the CI/CD when a new PR is opened.

**Comment by Kristian-ZH** [comment]
Some findings:

This is what a stuck build looks like in docker:
```
Nodes:
Name:      default
Endpoint:  default
Status:    running
Platforms: linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
```

The architecture of the infrastructure where the `docker buildx build` is called:
```
Linux a07256d2-83a9-4d1e-52f8-8ab845a970ca 5.10.109-garden-cloud-amd64 #1 SMP Debian 5.10.109-0gardenlinux2 (2022-04-07) x86_64 GNU/Linux
```

Docker version:
```
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 22:56:42 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:45 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309f
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Buildx plugin version:
```
github.com/docker/buildx v0.8.0 c8f7c1e93ffa9cfcf926cd3e6450af957f235b07
```
 - The latest version of the plugin is `v0.8.2` so it can be upgraded.

Reproducing the issue:
We reproduced the issue in the following way:
1. Exec on a job where the build is stuck.
2. Go to the PR directory
3. Run the command: `docker buildx build --platform linux/arm64 --target fluent-bit-plugin --progress=plain .`

**Comment by JordanJordanov** [comment]
Reverting ARM64 build (with https://github.com/gardener/logging/pull/145) until this issue is solved.

**Comment by Kristian-ZH** [comment]
This issue is already addressed
/close
