### ISSUE TITLE
CNCF Compliance

### ISSUE THREAD

**Issue by ThormaehlenFred** [gardener/logging#15]
The Gardener project informs its stakeholders in its [CNCF CII Badge](https://bestpractices.coreinfrastructure.org/en/projects/1822#security) under _Publicly known vulnerabilities fixed_, that it includes no unpatched vulnerabilities of medium or high severity that have been publicly known for more than 60 days. This repository has findings, which must be assessed by the component owner(s). Please contact me via e-mail and I will give you more information where and how to do the assessment.

**Comment by hoeltcl** [comment]
This issue must be resolved until **January 17th 2019** latest. Please contact [ThormaehlenFred]( https://github.com/ThormaehlenFred) or [hoeltcl](https://github.wdf.sap.corp/hoeltcl) if not already done.

**Comment by vlvasilev** [comment]
The findings have been assessed. They either do not apply to us or there is nothing to do about it since we are using third party images.
