### ISSUE TITLE
Missing logs for Gardener extension

### ISSUE THREAD

**Issue by vlvasilev** [gardener/logging#89]
**What happened**:
After an [issue](https://github.tools.sap/kubernetes-canary/issues-canary/issues/533#issuecomment-173929) with DNS entries it appears that there is no logs from the `dns-controller-manager`  older than 2021-02-05T07:07:24Z in the garden/loki-0 pod.
The current working pod is with `creationTimestamp: "2021-02-05T06:39:06Z"`.
The dns-controller-manager is 637d old.
The loki PVC is 181d old. and the PV garden/loki-loki-0 is 181d old.
Sts loki is 181d old. The pod garden/loki-0 is 26h old with 3 restarts.
```
    State:          Running
      Started:      Fri, 05 Feb 2021 09:08:05 +0200
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Fri, 05 Feb 2021 01:02:03 +0200
      Finished:     Fri, 05 Feb 2021 09:08:05 +0200
    Ready:          True
    Restart Count:  3
    Limits:
      cpu:     500m
      memory:  2800M
    Requests:
      cpu:        200m
      memory:     2G
```

**What you expected to happen**:
To have logs for the pas 14 days

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:
Seed aws-eu4 on canary

**Comment by Kristian-ZH** [comment]
This is a known issue, where the Loki's disk hits Inode limits.

This PR should resolve  issue: https://github.com/gardener/gardener/pull/3532
