### ISSUE TITLE
Fetch logs from shoot nodes

### ISSUE THREAD

**Issue by Kristian-ZH** [gardener/logging#93]
**What would you like to be added**:
A log processor should be installed on the shoot nodes to scrape processes like kubelet, docker, kernel and etc.

**Why is this needed**:
This change will help a lot in the investigation of the failed nodes.

**Comment by Kristian-ZH** [comment]
Progress can be tracked here: https://github.com/gardener/gardener/issues/3559

**Comment by vlvasilev** [comment]
/close
resolved by [#g/g3813](https://github.com/gardener/gardener/pull/3813)
