### ISSUE TITLE
Pluging file buffer is not removed from the file system when closing.

### ISSUE THREAD

**Issue by vlvasilev** [gardener/logging#96]
**What happened**:
When a file buffer is used for each client instance after closing the client the buffer is not removed from the file system.

**What you expected to happen**:
When a buffered Loki client is closed the underlying buffer is also removed from the file system.

**How to reproduce it (as minimally and precisely as possible)**:
Just activate the buffered client of the plugin.

**Anything else we need to know**:

**Environment**:

**Comment by JordanJordanov** [comment]
Already fixed with https://github.com/gardener/logging/pull/99
